### ISSUE TITLE
Split payments no me funciona

### ISSUE THREAD

**Issue by cherpsky** [epayco/epayco-php#10]
Tengo una duda en lo respectivo a split payments, tengo una tienda donde alojo vendedores, y quiero que cada vez que vendan me llegue un porcentaje del 2% a mí. Alguien puede poner un ejemplo concreto con datos 'reales' de prueba, quisiera un ejemplo tanto en card como en cash, ya que ninguna de las dos me está funcionando. Tengo dos cuentas creadas para simular la transaccion. 

Gracias

**Comment by pruebasepayco** [comment]
Buenas tardes

Reciba un cordial saludo

Efectivamente, el siguiente ejemplo sirve para ambos metodos, tarjeta de credito, cash e incluso PSE.
:

    "splitpayment" => "true",
    "split_app_id" => "P_CUST_ID_CLIENTE APPLICATION",
    "split_merchant_id" => "P_CUST_ID_CLIENTE COMMERCE",// este puede ser el mismo "split_app_id", y es a quien a sumira el costro de la comision de epayco
    "split_type" => "02", //02 =>% , 01 es un valor fijo por comision
    "split_primary_receiver" => "P_CUST_ID_CLIENTE APPLICATION", // el primer recibidor
    "split_primary_receiver_fee"=>"10", // el porcentaje o el valor fijo del primer resibidor
    "split_receivers" => array(array('id'=>'P_CUST_ID_CLIENTE 1ST RECEIVER','fee'=>'1000','fee_type' => '01')) //array que hace referencia a los recibidores, tener en cuenta que  si es por porcentaje debe ser un 90% repartido entre los resibidores para que la suma concuerde al 100% con el "split_primary_receiver_fee", de igual forma si es un valor fijo, la suma debe ser igual al valor del amount de la transaccion.



cuenta A =esta cuenta es el ecommerce o la plicacion y quien asume el costo de la comision
cuenta b =es un proveedor
    "splitpayment" => "true",
    "split_app_id" => "A",
    "split_merchant_id" => "A",
    "split_type" => "02",
    "split_primary_receiver" => "A",
    "split_primary_receiver_fee"=>"2",
    "split_receivers" => array(array('id'=>'B','fee'=>'98','fee_type' => '02'))

ejemplo de ganancia del 98% para la cuenta B y el 2% para la cuenta A teniendo el cuenta la comisión de epayco.


Si presentas alguna otra duda o no te queda claro el proceso de split payment por favor lo invitamos a agendar en el siguiente link una reunión de soporte técnico con nuestro equipo de desarrollo: https://calendly.com/epayco

Estaremos atentos.
