### ISSUE TITLE
Instalacion sin composer

### ISSUE THREAD

**Issue by H4K0** [epayco/epayco-php#11]
Hola, es posible instalar el SDK sin composer?

Actualmente el host es awardspace y no he logrado la instalación.

Revisando, el composer se encarga de  cargar la clase Epayco dentro del php del server. En este caso al no poder conseguir la instalación del composer, tengo la inquietud si puedo instalar el SDK sin necesidad de este. Los privilegios para correr composer de forma global sobre el server actualmente son insuficientes. Ya me puse en contacto con el soporte del hosting.

Estoy usando: awardspace y wordpress y si logro cargar el código de Epayco en la página sin plugins extra sería lo mejor.

<h4>Gracias de antemano.<h4/>

**Comment by JulianD** [comment]
Puedes descargar composer en tu máquina, instalar la librería y listo. La subes con el directorio vendor y en tu código te encargas de incluir el autoload.php de composer y debería funcionar sin problema.
