### ISSUE TITLE
epayco PSE transaccion despues de cargar los bancos 

### ISSUE THREAD

**Issue by darasat** [epayco/epayco-php#13]
Hola que tal buen dia👍

Primero felicito al equipo de Epayco por tan buen trabajo en su API rest.

Ahora les cuento un poco estoy intentando crear un servicio  para una aplicación, que conecta con Epayco siguiendo la documentación oficial en github.

https://epayco.github.io/documentation/#cuenta-bancaria-pse

sin embargo no encuentro una forma de enviar los parametros necesarios a la solicitud de PSE despues de listar los bancos.

estoy intentando realizar la siguiente petición por medio de POSTMAN (POST)

https://secure.payco.co/restpagos/pagos/debitos.json?public_key=0b862564a09d6d3fa15504aa8b07a349&banco=1007&factura=1472050778&descripcion=Pago%20pruebas&valor=10000&iva=0&baseiva=0&moneda=COP&tipo_persona=0&tipo_doc=CC&documento=10358519&nombres=PRUEBAS&apellidos=PAYCO&email=no-responder@payco.co&pais=CO&depto=Antioquia&ciudad=Medellin&telefono=0000000&celular=3010000001&direccion=Calle%2010%20&ip=186.116.10.133&url_respuesta=https://secure.payco.co/restpagos/testRest/endpagopse.php&url_confirmacion=https://secure.payco.co/restpagos/testRest/endpagopse.php&metodoconfirmacion=GET&enpruebas=FALSE&public_key=45819ac2ad3011c44630b60f67238b96&lenguaje=javascript&i=0000000000000000&p
pero la respuesta JSON que obtengo es:

{"success":false,"title_response":"Error","text_response":"No se pudo crear la transacci\u00f3n, por favor intente m\u00e1s tarde o comun\u00edquese con la empresa","last_action":"validation transaction","data":{"totalerrores":3,"errores":[{"codError":"E001","errorMessage":"Tipo Documento y Documento Requerido"},{"codError":"E006","errorMessage":"Tel\u00e9fono o Celular Requerido"},{"codError":"E021","errorMessage":"Moneda no soportada"}],"idfactura":false}}

algun tip para resolverlo?

muchas gracias.
cordial saludo.

**Comment by darasat** [comment]
para aquellos que tengan problemas con PSE para crear una transaccion (PASO 2)
https://secure.payco.co/restpagos/pagos/debitos.json?public_key=0b862564a09d6d3fa15504aa8b07a349&banco=1007&factura=1472050778&descripcion=Pago pruebas&valor=10000&iva=0&baseiva=0&moneda=COP&tipo_persona=0&tipo_doc=CC&documento=10358519&nombres=PRUEBAS&apellidos=PAYCO&email=no-responder@payco.co&pais=CO&depto=Antioquia&ciudad=Medellin&telefono=0000000&celular=3010000001&direccion=Calle 10 &ip=186.116.10.133&url_respuesta=https://secure.payco.co/restpagos/testRest/endpagopse.php&url_confirmacion=https://secure.payco.co/restpagos/testRest/endpagopse.php&metodoconfirmacion=GET&enpruebas=FALSE&public_key=45819ac2ad3011c44630b60f67238b96&lenguaje=javascript&i=0000000000000000&p

Prueben esta URL

**Comment by CristianVergara** [comment]
Buenas tardes, 

Lograste solucionarlo ?
