### ISSUE TITLE
Integración con Laravel - Error al recibir los datos de la compra desde ePayco

### ISSUE THREAD

**Issue by BrayanAngaritaR** [epayco/epayco-php#14]
Hola equipo de ePayco, he logrado integrar correctamente la pasarela de pago y me carga todo al Dashboard de ePayco sin problemas. Me muestra el estado: **Aceptada**, cuánto recibí, fecha de pago, fecha de caducidad, ... Todos los datos se envían correctamente hacia los servidores de ePayco (estoy usando el SDK para PHP).

Toda esa parte  funciona muy bien. Sin embargo, en la URL de respuesta no estoy recibiendo nada porque me dice **"Firma no valida"** aunque en Url confirmación me salen los datos correctos. Mi URL es: `https://cafe.test/payment/confirmation` y aún así no se está procesando nada.

Supuse que una vez que ePayco verificara que todo estaba en orden, enviaría los datos de la compra a esta URL (https://cafe.test/payment/confirmation) pero en mi caso no funciona.

Lo estoy haciendo como lo vi en un ejemplo y realmente no se recibe nada...

Así quedaría en Laravel. El error que obtengo es `Undefined index: x_ref_payco` y de ahí para abajo las siguientes variables.

`$p_cust_id_cliente = '00000';
      $p_key             = '00000000000000000000000000000000000000000';

      $x_cod_response = $request->x_cod_response;
      $x_ref_payco      = $request->x_ref_payco;
      $x_transaction_id = $request->x_transaction_id;
      $x_amount         = $request->x_amount;
      $x_currency_code  = $request->x_currency_code;
      $x_signature      = $request->x_signature;

      $signature = hash('sha256', $p_cust_id_cliente . '^' . $p_key . '^' . $x_ref_payco . '^' . $x_transaction_id . '^' . $x_amount . '^' . $x_currency_code);`

Si saben cómo obtener los datos les agradecería mucho. ¡Un abrazo!

**Comment by BrayanAngaritaR** [comment]
Ha pasado casi 1 año y aún no me responden 😮

**Comment by pruebasepayco** [comment]
Buenas tardes,

Cordial saludo.

Ofrecemos disculpas por la demora a la respuesta del requerimiento, informamos que la firma no coincide por que no esta mandando estos campos $p_cust_id_cliente = '00000';
$p_key = '00000000000000000000000000000000000000000'; de forma adecuada, esta información hace referencia al p_cust_id_cliente y p_key, estos valores lo puede encontrar en el dashboard, en el ejemplo de la pagina de confirmación que se encuentra en nuestra documentación, https://docs.epayco.co/payments/checkout#scroll-confirmation-page al inicio hay un comentario el cual indica claramente a que hace referencia estas variables, solicitamos amablemente ingresar a la cuenta de epayco, confirmar y configurar estos valores y realizar la respectivas pruebas de confirmación en el proyecto que realizas,informamos tambien que  puede utilizar la herramienta POSTMAN como ayuda para reenviar la data de cada transacción y simular la confirmación de esta, la data la puedes obtener en el detalle de la transacción desde el dashboard de epayco.  

En caso de que continúe el inconveniente lo invitamos a agendar en el siguiente link para una reunión con nuestro equipo de soporte técnico donde podrás realizar una video llamada y dar solución de forma efectiva al caso:https://calendly.com/epayco

 Agradecemos su comprensión, estaremos atentos a cualquier inquietud, sugerencia o inconveniente que presentes.

Cordial saludo.

**Comment by andresfmm** [comment]
hola amigo  espero estes bien,  hoy se me presento el mismo problema y logre resolverlo, primero que todo con todo es logico que las credenciales no van a ser $p_cust_id_cliente = '00000'  $p_key = '00000000000000000000000000000000000000000'; me extraña de epayco que responda eso nadie es tan tonto se entiende que es un ejemplo,  basicamente es un problema de epayco con laravel ellos tienen 2 ejemplo uno que tiene un script dentro de un form y seria la ruta asi data-epayco-confirmation="https://ejemplo.com/confirmacion" ahi no termina .php de esa manera no lo he usado, lo he usado de la otra manera  ejemplo confirmation: "http://secure2.payco.co/prueba_curl.php", es con este ultimo fue que lo resolvi  puedes ver que la extension es .php entonces debes tener esa ruta con la extension .php por ejemplo: confirmation:"https://payments.dominio.com/result.php"  ahora en ese subdominio pueder usar este ejemplo que muestra epayco: https://github.com/epayco/resources/blob/master/onePage/confirmation/confirmation.php apartir de ahi ya puede organizar los datos y envias formatiado los datos a tu controlador en laravel por ejemplo (https://cafe.test/payment/confirmation?$x_cod_response) y lo manejas en tu controlador como quieras asi lo resolvi rapido

espero te pueda servir o a otra persona tambien

muchas gracias

**Comment by neoacevedo** [comment]
El problema está en que epayco está haciendo una petición a la url de confirmación mediante **POST** pero todos los datos en realidad los está enviando como parámetros de la url por lo que, con Laravel, es imposible de capturarlos de manera adecuada, si no es usando la variable global **$_REQUEST**.
