### ISSUE TITLE
Obtener bancos PSE 

### ISSUE THREAD

**Issue by pechanxur** [epayco/epayco-php#15]
Estoy intentando traer los bancos como indica en su documentación pero esta me retorna error 500, agradeceria pudieran darme un ejemplo de cómo lograr esto (estoy usando laravel)

**Comment by pruebasepayco** [comment]
Buenas tardes.

Reciba un cordial saludo.

Ofrecemos disculpas por la tardanza a la respuesta del requerimiento, informamos que en el siguiente enlace puedes tener una guía para obtener los bancos: https://docs.epayco.co/methods/pse

Esperamos haber resuelto si inconveniente, estaremos atentos a cualquier sugerencia, solicitud o inquietud que presente
