### ISSUE TITLE
Funciones obsoletas 

### ISSUE THREAD

**Issue by CarmeloCampos** [epayco/epayco-php#20]
mcrypt_get_iv_size() is deprecated (McryptEncrypt.php on line 20)
Function mcrypt_get_key_size() is deprecated (McryptEncrypt.php on line 22)
Function mcrypt_encrypt() is deprecated (McryptEncrypt.php on line 35)

**Comment by pruebasepayco** [comment]
Buenas tardes,

Reciba un cordial saludo.

Informamos que se realizaron actualizaciones en la librería, por favor solicitamos realizar un composer update o clonarla nuevamente en el proyecto.

Agradecemos su comprensión, estaremos atentos a cualquier comentario o inquietud que presente.

**Comment by CarmeloCampos** [comment]
gracias <3
