### ISSUE TITLE
Id para almacenar

### ISSUE THREAD

**Issue by CarmeloCampos** [epayco/epayco-php#21]
Las transacciones por medio de Tarjeta de credito no guardan un x_id_factura haciendo que sea imposible actualizar cuando es cancelado, pagado o rechazado, sería bueno que dejen un id de factura único o en tal caso un x_ref_payco

**Comment by pruebasepayco** [comment]
Buenas tardes,

Reciba un cordial saludo.

Atendiendo al caso informamos que cuando se realiza alguna transacción ya sea por tarjeta de credito o algún otro método de pago a la url que tenga configurada como url de confirmación nuestro servidor envía un resultado con la información de cada transacción, uno de los parámetros que envía es el "x_id_invoice" que vienen ciento el id de la factura identificadora que envía el comercio, en caso de que no la envíen el sistema internamente generara una factura única, con esta información pueden realizar la respectiva actualización de el estado de la transacción, conformamos que los x_ref_payco son únicos y también x_id_invoice, por favor validar la siguiente información donde encontrara los datos que se retornan y un ejemplo de implantación de página de confirmación:
https://docs.epayco.co/payments/checkout#scroll-response-p

Agradecemos su comprensión, estaremos atentos a cualquier duda o comentario que tenga.

**Comment by CarmeloCampos** [comment]
Si, pero en el caso de pagar con tarjeta de credito cada operacion es diferente invoice

Entonces, si la transaccion que fue rechazada (se guarda para el usuario para que vea que fue rechazada) y el la misma operacion (ya que al correo manda un link para volver a intentar) el en el segundo intento paga por completo entonces el invoice que se manda a la url es diferente a la que fue rechazada, por ende no se puede actualizar el estatus

**Comment by pruebasepayco** [comment]
Buenos dias 

Cordial saludo.

Informo en el proyecto deben de relacionar el pedido con el invoice que ustedes crean, este invoice  deben de enviarlo en el atributo "bill", sino lo envian el sistema internamente crea uno y no podran relacionar el pedido, por ende deben de crear la factura unica ustedes para relacionar el pedido, el cual como anteriormente se habia informado llega en la confirmación  como "x_id_factura" , ya se realizaron las pruebas respectivas y el proceso es correcto, por favor realizar las respectivas pruebas e informarnos, Tener en cuenta bien la configuración de la página de confirmación: https://docs.epayco.co/payments/checkout#scroll-response-p

Estaremos atentos a cualquier inconvneiente o duda.
