### ISSUE TITLE
¿Tiempo?

### ISSUE THREAD

**Issue by CarmeloCampos** [epayco/epayco-php#22]
Hola, hice una transacción exitosa y aun no se refleja, cuanto tiempo se demora?
Mi aplicación ya no está en modo producción, ni en https://dashboard.epayco.co/ ni en la configuración de la clase del php. Por ende quiere decir que está trabajando adecuadamente. 
Hice una transacción exitosa y aun no se refleja, cuanto tiempo demora esto?

**Comment by pruebasepayco** [comment]
Buenas tardes,

Reciba un cordial saludo.

Por favor solicitamos enviarnos el ref_payco de la transacción, este lo obtienen des correo que se envia al cliente pagador y en la respuesta de la peticion. por favor ampliarnos la información a que te refieres que no se refleja?, en el dashboard de epayco o en el proyecto, tan amable validar que si este enviando las credenciales adecuadas.
$epayco = new Epayco\Epayco(array(
    "apiKey" => "YOU_PUBLIC_API_KEY",
    "privateKey" => "YOU_PRIVATE_API_KEY",
    "lenguage" => "ES",
    "test" => true
));

Estaremos atentos.

**Comment by pruebasepayco** [comment]
si continuas con el inconveniente lo invitamos a agendar una reunión en el siguiente enlace con el equipo de soporte técnico de epayco: https://calendly.com/epayco

**Comment by CarmeloCampos** [comment]
Si bueno, la cosa es que tengo un sistema de verificación en donde reviso la petición POST a la url que yo coloco. Ok esto bien, ya hoy empecé con producción (Osea, no en modo prueba o test) y estas dos transacciones me llegaron a la url con metodo post. En la variable x_respuesta que recibí, decía "Aceptada" y ya son dos transacciones así (diferentes precios y diferentes metodos). Mi pregunta es, ¿Se demora en aparecer mi balance en el dashboard?

**Comment by pruebasepayco** [comment]
Buenos dias,

Cordial saludo.

No, no se demora en aparecer el balance.
