### ISSUE TITLE
Listado de Bancos 

### ISSUE THREAD

**Issue by EfrainGaray** [epayco/epayco-php#3]
En la clase  Bank  el metodo pseBank que debería retornar la lista de bancos no funciona.
 
 /**
     * Return list all banks
     * @return object
     */
    public function pseBank()
    {
        return $this->request(
               "GET",
               "/restpagos/pse/bancos.json",
               $api_key = $this->epayco->api_key,
               $options = null,
               $private_key = $this->epayco->private_key,
               $test = $this->epayco->test,
               $switch = true,
               $lang = $this->epayco->lang
        );
    }

Ya que este no pasa la public_key por GET lo he arreglado así.
  
/**
     * Return list all banks
     * @return object
     */
   public function pseBank()
    {
        return $this->request(
               "GET",
               "/restpagos/pse/bancos.json?public_key=".$this->epayco->api_key,
               $api_key = $this->epayco->api_key,
               $options = null,
               $private_key = $this->epayco->private_key,
               $test = $this->epayco->test,
               $switch = true,
               $lang = $this->epayco->lang
        );
    }

**Comment by devepayco** [comment]
Hola, @EfrainGaray  este Issue ya fue resuelto. Por favor descargar la librería nuevamente. Le agradecemos amablemente por su reporte.
