### ISSUE TITLE
Document 0 is too large for the cluster

### ISSUE THREAD

**Issue by isideastech** [epayco/epayco-php#36]
Hola, pueden indicarme a que se debe el error?

{"status":false,"message":"Error inesperado","data":{"status":"error","description":"Error general contacte con soporte. Bulk write failed due to previous MongoDB\\Driver\\Exception\\RuntimeException: Document 0 is too large for the cluster. Document is 17583589 bytes, max is 16777216."}}

aparece al ejecutar esta función

$customer = $epayco->customer->create(array(
            "token_card" => $token_card,
            "name" => $name,
            "last_name" => $lastname,
            "email" => $email,
            "default" => true,
            "city" => $city,
            "address" => $address,
            "phone" => $phone,
            "cell_phone"=> $mobile
        ));

**Comment by JulianD** [comment]
Habría forma de saber que hay en cada una de las variables ?

**Comment by isideastech** [comment]
son datos normales, no tienen nada raro, lo que veo es que en la practica un usuario, solo crea una única vez el customerId y a ese customerId se le amarran multiples Tokens. el error fue dado por crear multiples customerId y tokens al mismo usuario
