### ISSUE TITLE
mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by lostlian** [epayco/epayco-php#9]
Al crear una transacción en PSE. Retorna el siguiente error:

**PHP VERSION 7.2.12**

```
"message": "Function mcrypt_get_iv_size() is deprecated",
"exception": "Epayco\\Exceptions\\ErrorException",
"file": ".../vendor/epayco/epayco-php/src/Client.php",
"line": 91,
```

**Comment by devepayco** [comment]
Hola, @lostlian  este Issue ya fue resuelto. Por favor descargar la librería nuevamente. Le agradecemos amablemente por su reporte.
